---
version: "2.0"

services:
  node:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.4-juno-lucina
    env:
      - MONIKER=node_1
      - CHAIN_URL=https://raw.githubusercontent.com/nullMames/juno-on-akash/main/chain.json
      # - MINIMUM_GAS_PRICES=0.025ujuno
      #  - MINIMUM_GAS_PRICES=0.025ujuno no gas required
      #  - SNAPSHOT_BASE_URL=https://cosmos-nodes.s3.ap-southeast-2.amazonaws.com/juno/lucina/data/juno_lucina_20210721.tar
      #  - SNAPSHOT_FORMAT=tar
      # Need to setup lite client on rpc and set new servers
      #  - STATESYNC_ENABLE=true
      #  - STATESYNC_RPC_SERVERS=<rpc.juno.omniflix.co:80,rpc.juno.giansalex.dev:80>
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 60Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1j2wkr3hshu44dxug4n3f27redumw0732p5sazg
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1
