version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: juno
        PROJECT_BIN: junod
        PROJECT_DIR: .juno
        VERSION: lucina
        REPOSITORY: https://github.com/CosmosContracts/Juno
        NAMESPACE: JUNOD
        WASMVM_VERSION: v0.14.0
    ports:
      - '26656:26656'
      - '26657:26657'
    environment:
      - MONIKER=node_1
      - CHAIN_URL=https://raw.githubusercontent.com/nullMames/juno-on-akash/main/chain.json
      #- SNAPSHOT_BASE_URL=https://drzerp.com/data
      #- SNAPSHOT_FORMAT=tar.gz
      #- STATESYNC_RPC_SERVERS=drzerp.com:26657,45.72.100.103:26657
      #- STATESYNC_SNAPSHOT_INTERVAL=500
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.juno
