version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: assetmantle
        PROJECT_BIN: mantleNode
        PROJECT_DIR: .mantleNode
        VERSION: v0.3.0-RC
        REPOSITORY: https://github.com/AssetMantle/node
        NAMESPACE: MANTLENODE
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - VALIDATE_GENESIS=0
      #- CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/assetmantle/chain.json
      - CHAIN_ID=mantle-1
      - GENESIS_URL=https://github.com/AssetMantle/genesisTransactions/mantle-1/final_genesis.json
      - P2P_PERSISTENT_PEERS=
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.mantleNode
