version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: akash
        VERSION: v0.12.1
        REPOSITORY: https://github.com/ovrclk/akash.git
        CHAIN_ID: akashnet-2
    environment:
      - MONIKER=akash_1
      - METADATA_URL=https://raw.githubusercontent.com/ovrclk/net/master/mainnet
      - MINIMUM_GAS_PRICES=0.025uakt
    volumes:
      - ./node-data:/root/.akash
