version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: sentinelhub
        VERSION: v0.6.2
        REPOSITORY: https://github.com/sentinel-official/hub.git
    environment:
      - MONIKER=node_1
      - METADATA_URL=https://raw.githubusercontent.com/tombeynon/cosmos-omnibus/install-and-config/sentinelhub/mainnet
      - GENESIS_URL=https://raw.githubusercontent.com/sentinel-official/launch/sentinelhub-2/sentinelhub-2/genesis.zip
      - MINIMUM_GAS_PRICES=0.1udvpn
      - VALIDATE_GENESIS=0
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.sentinelhub
