---
version: "2.0"

services:
  node:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.29-craft-v0.1.1
    env:
      - MONIKER=node_1
      # - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/craft/chain.json
      - CHAIN_ID=craft-testnet-1
      - GENESIS_URL=https://raw.githubusercontent.com/notional-labs/craft/4e804f74f3f2e8a68777e9533b1a89ca941474c3/networks/craft-testnet-1/genesis.json
      - P2P_PERSISTENT_PEERS=285e70f18b111c5676b13c044f2cebe664e53cb6@38.146.3.195:26656
      - MINIMUM_GAS_PRICE=0.02ucraft
      - CRAFTD_STAKING_BOND_DENOM=exp
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 40Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1
