---
version: "2.0"

services:
  node:
    image: ghcr.io/tombeynon/cosmos-omnibus:v0.0.2-rc9-osmosis-b702ebfdb139be0723a60f00c398aa2c2326b3cd
    env:
      - MONIKER=my-moniker-1
      - CHAIN_ID=osmo-testnet-3
      - P2P_SEEDS=42adaf5c53dee399987e3957e238638654262b99@159.65.233.217:26656
      # - P2P_PERSISTENT_PEERS=42adaf5c53dee399987e3957e238638654262b99@159.65.233.217:26656
      # - STATESYNC_RPC_SERVERS=159.65.233.217:26657
      - GENESIS_URL=https://transfer.sh/get/14mm7wK/genesis.json
      # - MINIMUM_GAS_PRICES=0.025uatom
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 60Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1
