---
version: "2.0"

services:
  node:
    image: ghcr.io/tombeynon/cosmos-omnibus:v0.0.2-rc11-osmosis-b702ebfdb139be0723a60f00c398aa2c2326b3cd
    env:
      - MONIKER=my-moniker-1
      - CHAIN_URL=https://raw.githubusercontent.com/sikkatech/tm-networks/master/osmo-testnet-3/chain.json
      # - STATESYNC_SNAPSHOT_INTERVAL=500
      # - STATESYNC_RPC_SERVERS=159.65.233.217:26657
      # - MINIMUM_GAS_PRICES=0.025uosmo
      # - DEBUG=1
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 40Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1
