---
version: "2.0"

services:
  node:
    image: ghcr.io/tombeynon/cosmos-omnibus:v0.0.2-rc15-osmosis-v1.0.1
    env:
      - MONIKER=my-moniker-1
      - CHAIN_URL=https://raw.githubusercontent.com/sikkatech/tm-networks/osmosis-1/osmosis-1/chain.json
      # - MINIMUM_GAS_PRICES=0.025uosmo
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 40Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1
