version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: nomic
        VERSION: eba76ebd6aac33e727c24f4a50558dbce442b823
        REPOSITORY: https://github.com/nomic-io/nomic
        NAMESPACE: TM
        PROJECT_DIR: .nomic-stakenet-2
        BASE_IMAGE: rustlang/rust:nightly
        INSTALL_PACKAGES: build-essential libssl-dev pkg-config clang
        BUILD_CMD: cargo install --locked --path .
        BUILD_PATH: /usr/local/cargo/bin
        INIT_CMD: nomic init
        CONFIG_DIR: tendermint/config
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/nomic/chain.json
      - VALIDATE_GENESIS=0
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.nomic-stakenet-2
