---
version: "2.0"

services:
  node:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.23-nomic-4aa1d001210f080cc12012eb7593c663404aa1d001210f080cc12012eb7593c66340fc7cb3
    env:
      - MONIKER=node_1
      - CHAIN_ID=nomic-stakenet
      - P2P_SEEDS=238120dfe716082754048057c1fdc3d6f09609b5@161.35.51.124:26656,a67d7a4d90f84d5c67bfc196aac68441ba9484a6@167.99.119.196:26659
      - VALIDATE_GENESIS=0
      - INIT_COMMAND=nomic init
      - CONFIG_DIR=/root/.nomic-stakenet/tendermint/config
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 40Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1
