---
version: "2.0"

services:
  node:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.23-nomic-develop
    env:
      - MONIKER=node_1
      - CHAIN_ID=nomic-stakenet-rc
      - P2P_SEEDS=dc7103629676c9bc02624887372c3e18a740c37d@167.99.228.240:26656
      - VALIDATE_GENESIS=0
      - INIT_COMMAND=nomic init
      - CONFIG_DIR=/root/.nomic-stakenet-rc/tendermint/config
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 40Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 100

deployment:
  node:
    dcloud:
      profile: node
      count: 1
