version: '3.4'

services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.0.29-nomic-eba76ebd6aac33e727c24f4a50558dbce442b823
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/nomic/chain.json
      - VALIDATE_GENESIS=0
    volumes:
      - ./node-data:/root/.nomic-stakenet-2
