name: publish
on:
  push:
    tags:
      - v*


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # hacks
          # - project: kava
          #   env:     KAVA
          #   version: v0.14.1
          #   bin:     kvd
          - project: akash
            project_bin: akash
            version: v0.12.1
            repository: https://github.com/ovrclk/akash.git
          - project: sentinelhub
            project_bin: sentinelhubd
            version: v0.5.0
            repository: https://github.com/sentinel-official/hub.git
          - project: gaia
            project_bin: gaiad
            version: v4.2.1
            repository: https://github.com/cosmos/gaia
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.CR_USER }}" --password-stdin
          docker build . --tag ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}-${{matrix.project}}-${{matrix.version}} \
            --build-arg PROJECT=${{matrix.project}} \
            --build-arg VERSION=${{matrix.version}} \
            --build-arg PROJECT_BIN=${{matrix.project_bin}} \
            --build-arg REPOSITORY=${{matrix.repository}}
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}-${{matrix.project}}-${{matrix.version}}
